apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jiob33788-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jiob33788-go 
  name: jiob33788-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jiob33788-go 
